name: Build, test and deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AZURE_API_NAME: loaning-bank-api
  AZURE_WEBAPP_PACKAGE_PATH: "."
  CONFIGURATION: Release
  DOTNET_VERSION: 6.0.x
  PROJECT_DIRECTORY: Src/LoaningBank.WebAPI

concurrency:
  group: build

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore "${{ env.PROJECT_DIRECTORY }}"

      - name: Build
        run: dotnet build "${{ env.PROJECT_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Test
        run: dotnet test "${{ env.PROJECT_DIRECTORY }}" --no-build

      - name: Publish
        run: dotnet publish "${{ env.PROJECT_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.PROJECT_DIRECTORY }}/Release"

      - name: Upload artifact for deployment job - .NET Core Web API
        uses: actions/upload-artifact@v3
        with:
          name: webapi
          path: "${{ env.PROJECT_DIRECTORY }}/Release/*"

  deploy:
    permissions:
      contents: none
    runs-on: windows-latest
    needs: build
    environment:
      name: Production
      url: https://loaning-bank-api.azurewebsites.net/

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: webapi

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_API_NAME }}
          publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
